language:
  - ruby
  - node_js

cache: bundler
bundler_args: --without development

rvm:
  - 2.2.3
node_js:
  - 0.10.0

addons:
  postgresql: '9.3'

before_script:
  - cp config/database.yml.travis config/database.yml
  - cp .env.sample .env
  - rm .rspec
  - bundle exec rake db:setup
  - npm install -g bower
  - bower install

notifications:
  email:
    recipients:
      - matheuslazzi@gmail.com

install:
  - npm install
  - bower install
