# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c805cdbbbc8b22568253220447121024892b9e906e223fde5bd82ed56b5af50b62f3afee50fc4cbabceb60e396d2c7f515f7956b6c0ff1574a9683b912af45e2

test:
  secret_key_base: eb6c4e55044f8f16b9122df0023f71a8a33b588d33a32dba1c14096bddc1a22a6dd48db1b5607607d4c4967cf9f2c275c66670cee7ffa9c7c5b4977454bfce16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
